### ISSUE TITLE
无法使用麦克风

### ISSUE THREAD

**Issue by Lewin671** [leogitpro/Hackintosh-DeskMini310#5]
无法使用上面的mic-in麦克风端口，下面那个带有音频输出的端口就可以检测到麦克风

**Comment by SnailDove** [comment]
> 无法使用上面的mic-in麦克风端口，下面那个带有音频输出的端口就可以检测到麦克风

这个而github主的deskmini交流群加不进去？你加进去了吗？

**Comment by Lewin671** [comment]
> > 无法使用上面的mic-in麦克风端口，下面那个带有音频输出的端口就可以检测到麦克风
> 
> 这个而github主的deskmini交流群加不进去？你加进去了吗？

加进去了!
