### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by eric-hang** [leogitpro/Hackintosh-DeskMini310#7]
请问10.15.6可以使用本efi吗？

**Comment by MinimalistMan** [comment]
我是使用15.4安装的，安装之后将clover升级到5120，然后直接系统升级了15.6，可以正常使用，只是在启动时会有个多国语言的错误提示，但不影响使用。这封邮件就是在15.6的macOS下回复的。
[image: image.png]

ericd <notifications@github.com> 于2020年8月24日周一 下午1:20写道：

**Comment by slarkcoder** [comment]
我已经装上了 10.15.7 了。。。

**Comment by yangatla** [comment]
请问使用此EFI包的时候，在dell的4K显示器下只能30Hz运行，这是正常情况吗？

**Comment by leogitpro** [comment]
这个是你的视频线的问题吧. 这个机器在 WINDOWS 下 HDMI 只能支持 30HZ, 60HZ 必须走 DP 口.
